### ISSUE TITLE
Error with gradio

### ISSUE THREAD

**Issue by shrishjain** [binh234/video2slides#1]
I am new to the application. I am trying to run it on windows 11, and I get the following error with gradio:

C:\temp\video2slides-main>gradio app.py
Watching: 'C:\temp\video2slides-main' 'C:\temp\video2slides-main'

Traceback (most recent call last):
  File "C:\temp\video2slides-main\app.py", line 226, in <module>
    demo.queue(concurrency_count=4).launch()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shris\AppData\Local\Programs\Python\Python312\Lib\site-packages\gradio\blocks.py", line 1882, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().

**Comment by binh234** [comment]
Hi, the issue has been fixed for gradio4

**Comment by shrishjain** [comment]
Do you mean I need to get the latest of gradio? Or last of video2slides?

**Comment by binh234** [comment]
Please download the latest code of video2slides to fix the issue
